name: Feature request
description: Suggest a new feature for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out as much as possible.
  - type: input
    id: title
    attributes:
      label: Feature title
      description: Short, descriptive title of the feature.
      placeholder: e.g. "Add dark mode"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Problem to solve
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature you’d like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you’ve considered?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.